name: 'Publish Conda package to Anaconda.org'
description: 'Build and Publish conda package to Anaconda'
author: 'Andrew Prokhorenkov, modified by Maxime Borry, Jamie Cash'
branding:
  icon: 'package'  
  color: 'blue'
inputs: 
  subDir:
    description: 'Sub-directory with conda recipe'
    default: '.'
  AnacondaToken:
    description: 'Anaconda access Token'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - ${{ inputs.subDir }}
  - ${{ inputs.AnacondaToken }}
